check: In flutter_version, verify version bound matches commit

diff --git a/tools/check b/tools/check
--- a/tools/check
+++ b/tools/check
@@ -220,7 +220,7 @@ run_test() {
 }
 
 # Check the Flutter version in pubspec.yaml is commented with a commit ID,
-# and the commit is from upstream main.
+# which agrees with the version, and the commit is from upstream main.
 run_flutter_version() {
     # Omitted from this files check:
     #   tools/check
@@ -231,14 +231,49 @@ run_flutter_version() {
     flutter_tree=$(flutter_tree)
     flutter_git=( git --git-dir="${flutter_tree}"/.git )
 
-    # Parse our Flutter version spec with its commit-ID comment.
-    local flutter_commit
-    flutter_commit=$(
+    # Parse our Flutter version spec and its commit-ID comment.
+    local parsed flutter_version flutter_commit
+    # shellcheck disable=SC2207 # output has controlled whitespace
+    parsed=( $(
         perl <pubspec.yaml -0ne '
-             print $1 if (/^  sdk: .*\n  flutter: \S+\s*# ([0-9a-f]{40})$/m)'
+             print "$1 $2" if (
+                 /^  sdk: .*\n  flutter: '\''>=(\S+)'\''\s*# ([0-9a-f]{40})$/m)'
+    ) ) || return
+    if [ -z "${#parsed[@]}" ]; then
+        echo >&2 "error: Flutter version spec not recognized in pubspec.yaml"
+        return 1
+    fi
+    flutter_version="${parsed[0]}"
+    flutter_commit="${parsed[1]}"
+
+    # Check the version name matches the commit ID.
+    local commit_described predicted_version
+    commit_described=$(
+        "${flutter_git[@]}" describe --tags "${flutter_commit}"
     ) || return
-    if [ -z "${flutter_commit}" ]; then
-        echo >&2 "error: Flutter commit spec not found in pubspec.yaml"
+    predicted_version=$(
+        echo "${commit_described}" \
+        | perl -lne 'print if (s
+             # This transformation is ad hoc.
+             # If we find cases where it fails, we can study
+             # how the `flutter` tool actually decides the version name.
+             <^(\d+\.\d+\.\d+-) (\d+) (\.\d+\.pre) -(\d+) -g[0-9a-f]+$>
+             <$1 . ($2 + 1) . $3 . "." . $4>xe)'
+    ) || return
+    if [ -z "${predicted_version}" ]; then
+        cat >&2 <<EOF
+error: unexpected 'git describe' result on Flutter commit in pubspec.yaml
+Commit ${flutter_commit} was described as: ${commit_described}
+EOF
+        return 1
+    fi
+    if [ "${flutter_version}" != "${predicted_version}" ]; then
+        cat >&2 <<EOF
+error: Flutter commit in pubspec.yaml seems to differ from version bound
+Commit ${flutter_commit} was described as: ${commit_described}
+We therefore expect the Flutter version name to be: ${predicted_version}
+But the Flutter version bound in pubspec.yaml is: ${flutter_version}
+EOF
         return 1
     fi
 
@@ -257,7 +292,7 @@ EOF
         return 1
     fi
 
-    if_verbose echo "OK Flutter commit ${flutter_commit}"
+    if_verbose echo "OK Flutter ${flutter_version} aka ${flutter_commit}"
 
     return 0
 }
