check: Add suite flutter_version

diff --git a/tools/check b/tools/check
--- a/tools/check
+++ b/tools/check
@@ -26,6 +26,7 @@ this_dir=${BASH_SOURCE[0]%/*}
 
 default_suites=(
     analyze test
+    flutter_version
     build_runner l10n drift pigeon icons
     android  # This takes multiple minutes in CI, so do it last.
 )
@@ -82,7 +83,7 @@ while (( $# )); do
         --all) opt_files=all; opt_all=1; shift;;
         --fix) opt_fix=1; shift;;
         --verbose) opt_verbose=1; shift;;
-        analyze|test|build_runner|l10n|drift|pigeon|icons|android|shellcheck)
+        analyze|test|flutter_version|build_runner|l10n|drift|pigeon|icons|android|shellcheck)
             opt_suites+=("$1"); shift;;
         *) usage;;
     esac
@@ -216,6 +217,49 @@ run_analyze() {
 run_test() {
     # no `flutter test --verbose` even when $opt_verbose; it's *very* verbose
     flutter test
+}
+
+# Check the Flutter version in pubspec.yaml is commented with a commit ID,
+# and the commit is from upstream main.
+run_flutter_version() {
+    # Omitted from this files check:
+    #   tools/check
+    files_check pubspec.yaml \
+    || return 0
+
+    local flutter_tree flutter_git
+    flutter_tree=$(flutter_tree)
+    flutter_git=( git --git-dir="${flutter_tree}"/.git )
+
+    # Parse our Flutter version spec with its commit-ID comment.
+    local flutter_commit
+    flutter_commit=$(
+        perl <pubspec.yaml -0ne '
+             print $1 if (/^  sdk: .*\n  flutter: \S+\s*# ([0-9a-f]{40})$/m)'
+    ) || return
+    if [ -z "${flutter_commit}" ]; then
+        echo >&2 "error: Flutter commit spec not found in pubspec.yaml"
+        return 1
+    fi
+
+    # Check the commit is an acceptable commit.
+    local commit_count
+    commit_count=$(
+        "${flutter_git[@]}" rev-list --count origin/main.."${flutter_commit}"
+    ) || return
+    if (( "${commit_count}" )); then
+        cat >&2 <<EOF
+error: Flutter commit spec in pubspec.yaml is not from upstream main.
+Commit ${flutter_commit} has ${commit_count} commits not in main:
+EOF
+        "${flutter_git[@]}" log --oneline --reverse \
+            origin/main.."${flutter_commit}"
+        return 1
+    fi
+
+    if_verbose echo "OK Flutter commit ${flutter_commit}"
+
+    return 0
 }
 
 # Whether the build_runner suite should run, given $opt_files.
@@ -456,6 +500,7 @@ for suite in "${opt_suites[@]}"; do
     case "$suite" in
         analyze)      run_analyze ;;
         test)         run_test ;;
+        flutter_version) run_flutter_version ;;
         build_runner) run_build_runner ;;
         l10n)         run_l10n ;;
         drift)        run_drift ;;
